### ISSUE TITLE
Add the option to run zipkin in a container in the example

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js-example#10]
Right now, running zipkin in the example requires to have JVM running, providing a docker way would be nice.

**Comment by eirslett** [comment]
>Or, if you're using docker:
>
>`$ docker run -d -p 9411:9411 openzipkin/zipkin`

That's what the README says. Is it unclear?

**Comment by jcchavezs** [comment]
I am blind. Closing this.
